#!/bin/bash

# Script para limpiar rastros de GitHub Copilot del repositorio
# Script to clean GitHub Copilot traces from the repository

echo "🔍 Analizando rastros de GitHub Copilot en el repositorio..."
echo "🔍 Analyzing GitHub Copilot traces in the repository..."
echo ""

# Check for copilot commits
echo "📋 Commits realizados por bots de Copilot:"
echo "📋 Commits made by Copilot bots:"
git log --author="copilot" --author="Copilot" --oneline || echo "   ✅ No se encontraron commits de Copilot"

echo ""

# Check for copilot branches
echo "🌿 Ramas con nombres relacionados a Copilot:"
echo "🌿 Branches with Copilot-related names:"
git branch -a | grep -i copilot || echo "   ✅ No se encontraron ramas con nombres de Copilot"

echo ""

# Check for AI-related comments in code
echo "💬 Comentarios relacionados con AI en el código:"
echo "💬 AI-related comments in code:"
find . -name "*.js" -o -name "*.jsx" -o -name "*.ts" -o -name "*.tsx" -o -name "*.py" | \
    xargs grep -n "copilot\|Copilot\|AI generated\|Generated by\|@ai\|TODO.*AI" 2>/dev/null || \
    echo "   ✅ No se encontraron comentarios relacionados con AI"

echo ""
echo "📝 Para limpiar el historial de commits, ejecuta:"
echo "📝 To clean the commit history, run:"
echo ""
echo "   # Crear rama limpia desde el último commit humano"
echo "   # Create clean branch from last human commit"
echo "   git checkout 9e42ccc"
echo "   git checkout -b main-clean"
echo ""
echo "   # Hacer push de la rama limpia"
echo "   # Push the clean branch"
echo "   git push origin main-clean"
echo ""
echo "   # En GitHub, cambiar la rama por defecto a 'main-clean'"
echo "   # In GitHub, change default branch to 'main-clean'"
echo ""
echo "   # Eliminar rama con rastros de Copilot"
echo "   # Delete branch with Copilot traces"
echo "   git push origin --delete copilot/fix-68c84a7a-bd0c-4689-9eac-cf3e8f9414ba"
echo ""
echo "⚠️  ADVERTENCIA: Esto reescribirá el historial. Coordina con tu equipo."
echo "⚠️  WARNING: This will rewrite history. Coordinate with your team."